spring.application.name=CRM


# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/CRM
spring.datasource.username=jonah
spring.datasource.password=""
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
jwt.secret=your-super-secret-key-must-be-at-least-32-characters-long
jwt.expiration=900000